import hashlib
import json
import re
import unittest
from unittest import mock

from bocco_bridge import reactions
from bocco_bridge.choreography import extract_motion_cues
from bocco_bridge.reactions import (
    ACCEL_PROBABLE_MISREAD_LIFT_REACTION_KEYS,
    DEFAULT_REACTION_PHRASES,
    REACTION_CAUTIONS,
    REACTION_DESCRIPTIONS,
    REACTION_EVENT_KEYS,
    REACTION_PHRASE_COUNT,
    REACTION_PHRASE_MAX_CHARS,
    REACTION_PHRASE_MIN_COUNT,
    SERIOUS_ACCEL_REACTIONS,
    accel_reaction_key,
    composed_persona_hash,
    parse_reaction_phrases,
    radar_reaction_key,
    reaction_generation_prompt,
    select_accel_kind,
)


# Anything that names which way the robot moved. The accelerometer cannot tell
# a pickup from a put-down, so a phrase built on either direction is wrong half
# the time by construction.
DIRECTION_WORDS = (
    "持ち上げ",
    "もちあげ",
    "持ちあげ",
    "抱っこ",
    "だっこ",
    "抱きあげ",
    "抱き上げ",
    "浮い",
    "浮か",
    "おろさ",
    "降ろさ",
    "下ろさ",
    "おろして",
    "置かれ",
    "置いて",
    "着地",
    "高いところ",
    "どこへ行く",
    "どこに行く",
    "運ばれ",
)
# Radar is a detection, not a certainty, and it fires on someone who has been
# in the room all along just as readily as on an arrival.
ARRIVAL_WORDS = ("おかえり", "はじめまして", "帰ってき", "かえってき", "起きた")
MARKDOWN_MARKERS = ("*", "_", "#", "`", "~", "[", "]", "<", ">", "|")


class ReactionBankPolicyTests(unittest.TestCase):
    def test_same_batch_priority_is_deterministic(self) -> None:
        self.assertEqual(select_accel_kind(("beaten", "lift", "shaken")), "shaken")
        self.assertEqual(
            select_accel_kind(("upside_down", "lift", "dropped")), "dropped"
        )
        self.assertEqual(select_accel_kind(("normal", "lying_down")), "normal")
        self.assertEqual(select_accel_kind(("normal", "lift")), "lift")

    def test_state_returns_map_only_to_the_existing_lift_bank_key(self) -> None:
        self.assertEqual(
            ACCEL_PROBABLE_MISREAD_LIFT_REACTION_KEYS,
            {"normal": "lift", "lying_down": "lift"},
        )
        self.assertEqual(accel_reaction_key("normal"), "lift")
        self.assertEqual(accel_reaction_key("lying_down"), "lift")
        self.assertEqual(
            set(REACTION_EVENT_KEYS),
            {
                "beaten",
                "lift",
                "shaken",
                "radar:morning",
                "radar:day",
                "radar:evening",
            },
        )

    def test_radar_time_buckets_cover_the_local_day(self) -> None:
        self.assertEqual(radar_reaction_key(7), "radar:morning")
        self.assertEqual(radar_reaction_key(13), "radar:day")
        self.assertEqual(radar_reaction_key(21), "radar:evening")
        self.assertEqual(radar_reaction_key(2), "radar:evening")

    def test_persona_hash_is_stable_and_content_sensitive(self) -> None:
        self.assertEqual(composed_persona_hash("同じ"), composed_persona_hash("同じ"))
        self.assertNotEqual(
            composed_persona_hash("persona one"), composed_persona_hash("persona two")
        )

    def test_persona_hash_is_not_the_bare_persona_digest(self) -> None:
        """The recipe has to be mixed in, or a prompt change cannot invalidate."""

        bare = hashlib.sha256("同じ".encode("utf-8")).hexdigest()
        self.assertNotEqual(composed_persona_hash("同じ"), bare)

    def test_changing_the_generation_prompt_invalidates_cached_banks(self) -> None:
        """The regression that shipped a better prompt to no effect.

        A bank is cached under this hash. When only the persona fed the hash,
        editing the prompt left every cached bank still matching its key, so a
        deployed robot kept speaking lines generated by the old prompt with
        nothing in the logs to indicate it.
        """

        before = composed_persona_hash("同じ")
        original = reactions._generation_recipe_fingerprint

        def patched_prompt(event_key: str, persona: str = "") -> str:
            return original_prompt(event_key, persona) + " Also mention the weather."

        original_prompt = reactions.reaction_generation_prompt
        reactions._generation_recipe_fingerprint.cache_clear()
        with mock.patch.object(reactions, "reaction_generation_prompt", patched_prompt):
            after = composed_persona_hash("同じ")
        reactions._generation_recipe_fingerprint.cache_clear()

        self.assertNotEqual(before, after)
        self.assertEqual(before, composed_persona_hash("同じ"))
        self.assertIs(reactions._generation_recipe_fingerprint, original)


class DefaultPhraseBankTests(unittest.TestCase):
    """The shipped fallbacks are what a fresh deployment says out loud."""

    def test_every_bank_is_full_and_unique(self) -> None:
        self.assertEqual(set(DEFAULT_REACTION_PHRASES), set(REACTION_EVENT_KEYS))
        for event_key in REACTION_EVENT_KEYS:
            with self.subTest(event_key=event_key):
                phrases = DEFAULT_REACTION_PHRASES[event_key]
                self.assertEqual(len(phrases), REACTION_PHRASE_COUNT)
                self.assertEqual(len(set(phrases)), REACTION_PHRASE_COUNT)

    def test_no_phrase_exceeds_the_speech_budget(self) -> None:
        for event_key, phrases in DEFAULT_REACTION_PHRASES.items():
            for phrase in phrases:
                with self.subTest(event_key=event_key, phrase=phrase):
                    self.assertTrue(phrase.strip())
                    self.assertLessEqual(len(phrase), REACTION_PHRASE_MAX_CHARS)
        for kind, phrase in SERIOUS_ACCEL_REACTIONS.items():
            with self.subTest(kind=kind):
                self.assertLessEqual(len(phrase), REACTION_PHRASE_MAX_CHARS)

    def test_no_phrase_carries_markup_or_an_unspeakable_symbol(self) -> None:
        spoken = (
            *(
                phrase
                for phrases in DEFAULT_REACTION_PHRASES.values()
                for phrase in phrases
            ),
            *SERIOUS_ACCEL_REACTIONS.values(),
        )
        for phrase in spoken:
            with self.subTest(phrase=phrase):
                for marker in MARKDOWN_MARKERS:
                    self.assertNotIn(marker, phrase)
                self.assertIsNone(re.search(r"[A-Za-z0-9]", phrase))

    def test_every_motion_cue_in_a_phrase_resolves(self) -> None:
        """A cue name that does not resolve is stripped and the gesture lost."""

        for phrases in DEFAULT_REACTION_PHRASES.values():
            for phrase in phrases:
                with self.subTest(phrase=phrase):
                    extraction = extract_motion_cues(phrase)
                    # No bracketed token survives stripping as spoken text, and
                    # any cue the phrase does carry must have been recognised.
                    self.assertEqual(extraction.text, phrase)
                    self.assertEqual(extraction.cues, ())

    def test_handled_bank_never_asserts_a_direction(self) -> None:
        """normal/lying_down share this bank, so no line may pick a direction."""

        for phrase in DEFAULT_REACTION_PHRASES[accel_reaction_key("normal")]:
            for word in DIRECTION_WORDS:
                with self.subTest(phrase=phrase, word=word):
                    self.assertNotIn(word, phrase)

    def test_radar_banks_never_assert_an_arrival(self) -> None:
        for event_key in ("radar:morning", "radar:day", "radar:evening"):
            for phrase in DEFAULT_REACTION_PHRASES[event_key]:
                for word in ARRIVAL_WORDS:
                    with self.subTest(phrase=phrase, word=word):
                        self.assertNotIn(word, phrase)

    def test_serious_kinds_keep_their_fixed_reassuring_replies(self) -> None:
        self.assertEqual(set(SERIOUS_ACCEL_REACTIONS), {"dropped", "upside_down"})
        for kind, phrase in SERIOUS_ACCEL_REACTIONS.items():
            with self.subTest(kind=kind):
                self.assertIsInstance(phrase, str)
                self.assertTrue(phrase.strip())
        self.assertNotIn("dropped", DEFAULT_REACTION_PHRASES)
        self.assertNotIn("upside_down", DEFAULT_REACTION_PHRASES)


class ReactionGenerationPromptTests(unittest.TestCase):
    def test_prompt_carries_the_active_persona(self) -> None:
        persona = "あなたはいたずら好きで、ちょっとおしゃべりなロボットです。"
        for event_key in REACTION_EVENT_KEYS:
            with self.subTest(event_key=event_key):
                prompt = reaction_generation_prompt(event_key, persona=persona)
                self.assertIn(persona, prompt)

    def test_prompt_states_the_count_cap_and_situation(self) -> None:
        for event_key in REACTION_EVENT_KEYS:
            with self.subTest(event_key=event_key):
                prompt = reaction_generation_prompt(event_key, persona="性格")
                self.assertIn(str(REACTION_PHRASE_COUNT), prompt)
                self.assertIn(str(REACTION_PHRASE_MAX_CHARS), prompt)
                self.assertIn(REACTION_DESCRIPTIONS[event_key], prompt)
                self.assertIn(REACTION_CAUTIONS[event_key], prompt)
                self.assertIn("JSON array", prompt)

    def test_prompt_forbids_direction_words_for_the_handled_bank(self) -> None:
        prompt = reaction_generation_prompt("lift", persona="性格")
        self.assertIn("持ち上げられた", prompt)
        self.assertIn("おろされた", prompt)

    def test_prompt_survives_an_empty_persona(self) -> None:
        prompt = reaction_generation_prompt("beaten", persona="   ")
        self.assertIn("JSON array", prompt)
        self.assertNotIn("verbatim", prompt)


class ReactionBankParserTests(unittest.TestCase):
    def _bank(self, count: int = REACTION_PHRASE_COUNT) -> tuple[str, ...]:
        return tuple(f"はんのう{item}" for item in range(count))

    def test_parser_accepts_a_full_bank(self) -> None:
        valid = self._bank()
        self.assertEqual(
            parse_reaction_phrases(json.dumps(valid, ensure_ascii=False)), valid
        )

    def test_parser_accepts_a_short_but_usable_bank(self) -> None:
        valid = self._bank(REACTION_PHRASE_MIN_COUNT)
        self.assertEqual(
            parse_reaction_phrases(json.dumps(valid, ensure_ascii=False)), valid
        )

    def test_parser_trims_an_over_long_bank_to_the_chosen_count(self) -> None:
        parsed = parse_reaction_phrases(
            json.dumps(self._bank(REACTION_PHRASE_COUNT + 6), ensure_ascii=False)
        )
        self.assertEqual(len(parsed), REACTION_PHRASE_COUNT)

    def test_parser_drops_duplicate_and_over_long_lines(self) -> None:
        noisy = [
            *self._bank(),
            self._bank()[0],
            "長" * (REACTION_PHRASE_MAX_CHARS + 1),
            "   ",
        ]
        parsed = parse_reaction_phrases(json.dumps(noisy, ensure_ascii=False))
        self.assertEqual(parsed, self._bank())

    def test_parser_rejects_unusable_output(self) -> None:
        invalid = (
            "not json",
            json.dumps(["一"] * REACTION_PHRASE_COUNT, ensure_ascii=False),
            json.dumps(
                list(self._bank(REACTION_PHRASE_MIN_COUNT - 1)), ensure_ascii=False
            ),
            json.dumps(
                ["長" * (REACTION_PHRASE_MAX_CHARS + 1)] * REACTION_PHRASE_COUNT,
                ensure_ascii=False,
            ),
            json.dumps({"phrases": list(self._bank())}, ensure_ascii=False),
            json.dumps([1, 2, 3], ensure_ascii=False),
        )
        for output in invalid:
            with self.subTest(output=output), self.assertRaises(ValueError):
                parse_reaction_phrases(output)


if __name__ == "__main__":
    unittest.main()
